# This hosts file is generated by the terraform script which provisioned this server, based on the app requirements. ${new_line}
# Any modifications to the file may break the application functionality ${new_line}
127.0.0.1       localhost localhost.localdomain.com ${new_line}
::1             localhost ${new_line}
# ${new_line}
${data_catalog_ip} ${data_catalog_hostname} ${data_catalog_hostname}.localdomain.com ${new_line}
${ambari_ip} ${ambari_hostname} ${ambari_hostname}.localdomain.com ${new_line}
${pcr_s_ip} ${pcr_s_hostname} ${pcr_s_hostname}.localdomain.com ${new_line}
${axon_ip} ${axon_hostname} ${axon_hostname}.localdomain.com ${new_line}
${new_line}
